#!/usr/bin/perl -w
#
# Given the holarctic list XLS, then parsed by py_xls2cvs,
# parse it to a gavia(5) species list.
#
use strict;

while(<>) {
    s/\\xe5/å/g;
    s/\\xe4/ä/g;
    s/\\xf6/ö/g;
    s/\\xe9/é/g;
    s/\\xfc/ü/g;

    my @v = split /"/;

    my ($latin, $se);

    if(@v==7) {
	($latin, $se) = ($v[1], $v[3]);
    }
    elsif(@v==9) {
	if($v[1] =~ /[A-Z]\w+ \w+/) {
	    ($latin, $se) = ($v[1], $v[3]);
	}
	else {
	    ($latin, $se) = ($v[3], $v[5]);
	}
    }
    elsif(@v==11) {
	($latin, $se) = ($v[3], $v[5]);
    }
    else {
	die;
    }

    printf("%-32s(%s)\n", $se, $latin);
}
