.\" $Id: gavia_grep.1,v 1.6 2000-12-04 21:23:21 grahn Exp $
.\" 
.\"
.TH gavia_grep 1 "JULY 1999" Unix "User Manuals"
.SH "NAME"
gavia_grep \- filter Gavia books through regular expression
.SH "SYNOPSIS"
.B gavia_grep [-v|-V]
.I pattern
.I bookfiles
.B ...
.SH "DESCRIPTION"
.B gavia_grep
filters one or more Gavia book files
given on the command line.
Any excursion matching the pattern
(in place, date, time, weather, observers,
comments, species name or species comment)
is passed through.
.PP
A dash '-' denotes standard input.
Standard input is also used if no
book files are mentioned.
The resulting aggregate book is then written to
standard output, as a
Gavia book (i.e. binary).
.PP
The pattern syntax follows that of regex(7).
.SH "OPTIONS"
.IP -v
Inverts handling,
so that excursions not matching the pattern
are passed through.
.IP -V
Print version information and exit.
.SH "FILES"
N/A.
.SH "ENVIRONMENT"
The current locale settings might influence certain aspects.
TBD.
.SH "DIAGNOSTICS"
TBD.
.SH "BUGS"
Error handling and error reporting is rudimentary, at the most.
Bad file contents may give unrecoverable errors.
The Gavia book format is fucked up.
.B gavia_grep
is written in C++ and might be
fragile and/or non-portable because of that.
.SH "AUTHOR"
Jorgen Grahn <jgrahn@algonet.se>
.SH "SEE ALSO"
.BR gavia (1),
.BR gavia_add (1),
.BR gavia_cat (1),
.BR gavia_sort (1),
.BR gavia_stat (1),
.BR regex (7)
