.\" $Id: gavia_stat.1,v 1.9 2008-01-03 09:38:19 grahn Exp $
.\" 
.\"
.TH gavia_stat 1 "APR 2018" Gavia "User Manuals"
.SH "NAME"
gavia_stat \- extract species info from a Gavia book
.SH "SYNOPSIS"
gavia_stat file ...
.SH "DESCRIPTION"
gavia_stat takes one or more files (stdin if none given) in
.BR gavia (5)
format and outputs basically the same data but
rearranged with the species name as major key.
.PP
Fields are colon-separated:
.IP
.ft CW
species : date : place : number : comment : observers
.PP
For example,
.IP
.ft CW
storskrake : 20000401 : Toarpsdammen, Oxie :  1: 1 hona : JoG
.PP
This makes further manipulation and mangling using standard
utilites and customized scripts easy. 
.SH "EXAMPLES"
.IP
.ft CW
gavia_stat obsbok | sort
.PP
List all observations sorted by species, then by date.
.IP
.ft CW
gavia_stat obsbok | sort -k2 -t:
.PP
List all observations, sorted by date.
.IP
.ft CW
gavia_stat obsbok | egrep ^enkelbeckasin | sort
.PP
List all observations of 'enkelbeckasin', sorted by date.
.IP
.ft CW
gavia_stat obsbok | awk -F: '{print $1 $4;}' | sort
.PP
List all observations, with species and number of individuals,
sorted by name. (This won't work if there is a colon ':' in the
excursion name.)
.IP
.ft CW
gavia_stat obsbok | egrep -c ^enkelbeckasin
.PP
Count the number of observations (
.I not
the individuals)
of 'enkelbeckasin'.
.SH "AUTHOR"
J\(:orgen Grahn <grahn+src@snipabacken.se>
.SH "SEE ALSO"
.BR gavia_cat (1),
.BR gavia_grep (1),
.BR gavia_sort (1),
.BR gavia (5)
