.\" $Id: gavia_stellata.1,v 1.9 2008-01-03 09:38:19 grahn Exp $
.\" 
.\"
.TH gavia_stellata 1 "APR 2018" Gavia "User Manuals"
.
.
.SH "NAME"
gavia_stellata \- add excursions to a Gavia book
.
.SH "SYNOPSIS"
.B gavia_stellata
[\-f
.IR template ]
.I file
.
.SH "DESCRIPTION"
.B gavia_stellata
makes it convenient to add
excursions to a Gavia book, as described in
.BR gavia (5).
.LP
An excursion template file,
.IR ~/.gavia_template ,
is read into a text editor (e.g. emacs), with the current date filled in.
.LP
When the user has edited and saved it,
.I gavia_stellata
strips away all non-selected species and fires up the editor again,
so that the user can add numbers and comments
without being distracted by the full species list.
.LP
When the user saves the excursions for the second and last time,
.I gavia_stellata
adjusts column widths to make it more readable,
appends the result to
.I file
and exits.
.
.SH "OPTIONS"
.IP \-f\ \fItemplate
Use
.I template
instead of
.I ~/.gavia_template
or
.IR lib/gavia/default .
.
.SH "FILES"
.TP
.I ~/.gavia_template
Personal excursion template file. May contain only a subset of
all species. Fields, e.g. 'observers', may be pre-filled.
.TP
.I lib/gavia/default
Global excursion template file, used if the personal template isn't
available
and none has been given using the
.B \-f
flag.
.TP
.I lib/gavia/species
The list of supported taxa and their taxonomic ordering.
Used by
.I gavia_stellata
only to issue warnings about misspelled species names.
.
.SH "ENVIRONMENT"
.IP GAVIAEDITOR
Specifies the editor to use.
If not set, VISUAL or EDITOR is used instead.
If none of these are set, the default is
.BR emacs .
.LP
If the editor is
.BR emacs ,
the original file is opened in a second buffer in the background, so that
.I "M-x dabbrev-expand"
can fetch words (like place names) from earlier entries and make input
easier and less prone to spelling errors.
.
.SH "AUTHOR"
J\(:orgen Grahn
.IR \[fo]grahn@snipabacken.se\[fc] .
.
.SH "SEE ALSO"
.BR gavia (1),
.BR gavia (5)
