.\" $Id: gavia_add.1,v 1.14 2008-01-03 09:38:19 grahn Exp $
.\" 
.\"
.TH gavia_add 1 "JULY 1999" Gavia "User Manuals"
.SH "NAME"
gavia_add \- add excursions to a Gavia book
.SH "SYNOPSIS"
gavia_add [\-v] [bookfile]
.SH "DESCRIPTION"
gavia_add reads excursion descriptions in ''Gab'' format
from standard input, and writes it to standard output
in ''Gavia book'' format.
If the optional argument
.I bookfile
is given, the contents of that book
is prepended to the output.
.SH "OPTIONS"
.IP \-v
Print version information.
.SH "INPUT FORMAT"
See
.BR gavia (5).
.SH "FILES"
.TP
.I lib/gavia/species
The list of supported taxa and their taxonomic ordering.
.SH "ENVIRONMENT"
The current locale settings might influence certain aspects.
TBD.
.SH "DIAGNOSTICS"
Badly-formed standard input causes a message on stderr.
The original book is output unchanged.
.SH "BUGS"
Error handling and error reporting is rudimentary, at the most.
Bad file contents give unrecoverable errors.
The Gavia book format is fucked up.
.SH "AUTHOR"
J\(:orgen Grahn <grahn+src@snipabacken.se>
.SH "SEE ALSO"
.BR gavia_cat (1),
.BR gavia_grep (1),
.BR gavia_sort (1),
.BR gavia_stat (1),
.BR gavia (5)
