.\" $Id: gavia_add.1,v 1.8 2001-06-17 20:51:37 grahn Exp $
.\" 
.\"
.TH gavia_add 1 "JULY 1999" Gavia "User Manuals"
.SH "NAME"
gavia_add \- add excursions to a Gavia book
.SH "SYNOPSIS"
gavia_add [-v] bookfile
.SH "DESCRIPTION"
gavia_add takes a single Gavia book as an argument.
It then reads more excursion descriptions in a special text format
(see below for a description) from standard input, and
writes the book with the extra excursions added
to standard output.
.SH "OPTIONS"
.IP -v
Print version information.
.SH "INPUT FORMAT"
See
.BR gavia (5).
.SH "FILES"
N/A.
.SH "ENVIRONMENT"
The current locale settings might influence certain aspects.
TBD.
.SH "DIAGNOSTICS"
Badly-formed standard input causes a message on stderr.
The original book is output unchanged.
.SH "BUGS"
Error handling and error reporting is rudimentary, at the most.
Bad file contents give unrecoverable errors.
The Gavia book format is fucked up.
.SH "AUTHOR"
Jörgen Grahn <jgrahn@algonet.se>
.SH "SEE ALSO"
.BR gavia_cat (1),
.BR gavia_grep (1),
.BR gavia_sort (1),
.BR gavia_stat (1),
.BR gavia (5)
