.\" $Id: gavia_sort.1,v 1.6 2000-12-28 19:55:33 grahn Exp $
.\" 
.\"
.TH gavia_sort 1 "NOVEMBER 1999" Unix "User Manuals"
.SH "NAME"
gavia_sort \- sort excursions in Gavia books
.SH "SYNOPSIS"
.B gavia_sort [-dpv]
.I bookfiles
.B ...
.SH "DESCRIPTION"
.B gavia_sort
sorts one or more Gavia book files
given on the command line.
Excursions can be made to sort by
place, then date or
date, then place.
.PP
A dash '-' denotes standard input.
Standard input is also used if no
book files are mentioned.
The resulting book is then written to
standard output, as a
Gavia book (i.e. binary).
.SH "OPTIONS"
.IP -d
Use date as primary sorting key (default).
.IP -p
Use place as primary sorting key.
.IP -v
Print version information and exit.
.SH "FILES"
N/A.
.SH "ENVIRONMENT"
The current locale settings might influence certain aspects.
TBD.
.SH "DIAGNOSTICS"
TBD.
.SH "BUGS"
Error handling and error reporting is rudimentary, at the most.
Bad file contents may give unrecoverable errors.
The Gavia book format is fucked up.
.B gavia_sort
is written in C++ and might be
fragile and/or non-portable because of that.
.SH "AUTHOR"
Jörgen Grahn <jgrahn@algonet.se>
.SH "SEE ALSO"
.BR gavia_add (1),
.BR gavia_cat (1),
.BR gavia_grep (1),
.BR gavia_stat (1)
