.\" $Id: gavia.1,v 1.1 2001-06-19 21:09:26 grahn Exp $
.\" 
.\"
.TH gavia 1 "JUN 2001" Gavia "User Manuals"
.SH "NAME"
gavia \- bird notebook tools
.SH "DESCRIPTION"
Gavia is a set of tools used to create,
share, maintain and present bird notebooks.

It is centered around the
.I excursion
concept, i.e. you write down where you were, the time and day,
weather et cetera, and what species you saw.

A Gavia book may be shared between several birders using tools such as
.BR cvs (1).
.SH "AUTHOR"
Jörgen Grahn <jgrahn@algonet.se>
.SH "SEE ALSO"
.BR gavia_add (1),
.BR gavia_cat (1),
.BR gavia_grep (1),
.BR gavia_sort (1),
.BR gavia_stat (1),
.BR gavia_stellata (1),
.BR gavia (5)
