.ss 12 0
.de BP
.IP \\fB\\$*
..
.
.
.TH gavia 5 "JUN 2013" Gavia "User Manuals"
.
.
.
.SH "NAME"
gavia \- Gavia bird notebook format
.
.SH "DESCRIPTION"
.
A Gavia bird notebook file
(referred to as a \(lqGab\(rq file in some of the documentation)
describes
.B excursions
(birding trips)
and the bird species (and other taxa) sighted during them.
.LP
It replaces the birdwatcher's traditional field notebook.
.LP
The input format is designed so that
a user can start with a template file
and quickly edit it, marking the species
seen during an excursion
and filling in any extra information.
.
.
.
.SS "General format"
Input is line-oriented.
Blank lines are ignored, and
so are comment lines (prefixed with a hash (#) sign).
Case is significant.
.LP
.I "Continuation lines"
are supported.
That is, fields may be broken into several lines if line two, three and so on
are indented with whitespace, for example:
.IP
.nf
.ft CW
place: M\(:ossebergsparken,
       Djurparken, \(oAngermanland
date : 2006-02-16
.fi
.LP
The input consists of a series of excursions,
each looking like
.IP
.nf
.ft CW
{
header fields
}{
sightings
}
.fi
.
.SS "Header fields"
Header fields are
.
.BP place
The place(s) visited during the excursion.
.
.BP date
The date, preferably as
.IR yyyy-mm-dd ,
but also six-digit form
.RI ( yymmdd ),
eight-digit form
.RI ( yyyymmdd ),
or whatever you like.
.BP
A date field at least
.I starting
with a date on one of these forms can be used for
sorting by tools like
.BR gavia_sort (1).
.
.BP time
The time of day or duration.
.
.BP observers
The people present.
.
.BP weather
The weather.
.
.BP comments
Anything else worth noting which does not concern a specific sighting.
.PP
For example:
.IP
.nf
.ft CW
place        : Hills golfbana, inre delen av Alveredsdalen
date         : 2013-03-09
time         : 8.10--9.50
observers    : J\(:oG
weather      : sol, barmark och frost; viss vind
comments     :
.fi
.LP
Headers are generally optional, and can be left unfilled or left out entirely \-
or you can invent additional fields.
However, the
.BR place ,
.B date
and
.B observers
fields may not be left unfilled; in the unlikely case that you don't want them,
you should remove them entirely.
.LP
The six standard header fields may not be repeated.
.
.SS "Sightings"
Sightings have the format
.IP
.ft CW
species name: mark: number of individuals: comment
.LP
For example:
.IP
.nf
.ft CW
flods\(oangare  :#: 2: 1 sj SO tippkanten vid dungen;
                    1 sj mellan Sn\(:otippen och grandungen.
.fi
.LP
The species or taxon name should be one of those defined by Gavia
(i.e. the file
.IR lib/gavia/species ),
but others are acceptable too.
Some tools will generate a warning message for unknown names.
.LP
A sighting can be unfilled (neither mark, number nor comment),
in which case it
is not to be regarded as included in the excursion.
The only purpose of the mark (typically a `#') is to include a species
without giving the number of individuals or a comment.
.
.
.
.SH "LANIUS BOOK"
Earlier versions of
.B gavia
also used a binary file format inherited from its
Commodore-Amiga-based predecessor,
.BR Lanius .
No such files have existed in the wild for a decade or so, and support was dropped
with Gavia 4.0.  Good riddance.
.
.
.SH "AUTHOR"
J\(:orgen Grahn
.IR \[fo]grahn+src@snipabacken.se\[fc] .
.
.
.SH "SEE ALSO"
.BR gavia (1),
.BR gavia_stellata (1).
