.\" $Id: gavia_gab2roff.1,v 1.6 2008-01-03 09:38:19 grahn Exp $
.\" 
.\"
.TH gavia_gab2roff 1 "JUN 2013" Gavia "User Manuals"
.SH "NAME"
gavia_gab2roff, gavia_gab2html \- exporting Gavia data to various formats
.SH "SYNOPSIS"
.B gavia_gab2roff
.I files
.B ...
.br
.B gavia_gab2html
.I files
.B ...
.SH "DESCRIPTION"
These programs read ''gab''-formatted text from
.IR files \(emor
from standard input\(emand reformat it in different ways.
.PP
.B gavia_gab2roff
produces groff/nroff/troff source, suitable for
transforming into e.g. formatted plain text,
Postscript or PDF.
It relies heavily on the
.B tbl
preprocessor, for creating tables.
.PP
.B gavia_gab2html
produces HTML (HTML 4.01 strict), for viewing with
a web browser.
.SH "AUTHOR"
J\(:orgen Grahn <grahn+src@snipabacken.se>
.SH "SEE ALSO"
.BR gavia_cat (1),
.BR gavia (5),
.BR gavia (1),
.BR nroff (1),
.BR troff (1)
