.\" $Id: gavia.5,v 1.4 2002-07-20 20:51:26 grahn Exp $
.\" 
.\"
.TH gavia 5 "JUN 2001" Gavia "User Manuals"
.SH "NAME"
gavia \- Gavia bird note book formats
.SH "DESCRIPTION"
Two different file formats are used with Gavia:
the text format tentatively called ''gab'', and
the older, binary format ''Lanius book''.
Different Gavia commands work on different kinds of
files.
.SH "GAB FILES"
The ''Gab'' input format is designed so that
a user can start with a template file
and quickly edit it, marking the species
seen during an excursion
and filling in any extra information.

Blank lines are ignored.
Comment lines (prefixed with a hash (#) sign)
are ignored.
Case and extra blank space
is not significant except in species names
(which are by convention in all lowercase)
and user-supplied data.

Input is line-oriented; fields may never
be broken into several lines.

The input consists of a series of excursions,
each looking like
.IP
.ft CW
{
.br
excursion fields
.br
}{
.br
species fields
.br
}
.LP
Excursion fields are

Place: <place description>
.br
Date: <yyyymmhh>
.br
Time: <description of time out>
.br
Observers: <names of any persons involved>
.br
Weather: <weather description>
.br
Comments: <anything else you want to note>

All but place and date are optional and
can be left unfilled or left out entirely.

Species fields have the format
.IP
.ft CW
<species name>: <mark>: <number of individuals>: <comment>
.LP
The species name must be exactly one of those defined internally
in gavia_add.

A species field can be unfilled, in which case that species
is not to be regarded as included in the excursion.

The number of individuals and/or comment may still be left out,
but in that case the user must fill in the mark field
with some non-blank characters, for example an '#'.
.SH "LANIUS BOOK"
The binary Lanius book format was inherited by Gavia from its
Commodore-Amiga-based predecessor.

Integer values are stored in big-endian (network) byteorder.
Strings are encoded in the
.BR ISO_8859-1 (7)
charset.
They start with a 2-octet length and are not NUL-terminated.

The book itself consists of a preamble, the string
.LP
.ft CW
Lanius Book v1.0
.LP
followed by zero or more excursion records and terminated by
.LP
.ft CW
NIL:
.LP
A excursion record consists of the sequence:
.IP \(bu
An empty string.
.IP \(bu
Place (string).
.IP \(bu
Date, in seconds since Jan 1, 1978 00:00:00, as a 4-octet integer.
Considering the Amiga's system clock always lives in local time
(including DST) this is obviously not a good way to encode dates.
.IP \(bu
Time (string).
.IP \(bu
Observers (string).
.IP \(bu
Weather (string).
.IP \(bu
Comments (string).
.IP \(bu
An empty string.
.IP \(bu
A 200-octet bitmap identifying the birds seen,
arranged so that MSB of the first octet represents the first bird,
LSB represents the eighth bird, and so on.
Undefined positions are zeroed.
The mapping from number to species name, defined by
the file
.I lib/gavia/species
in a Gavia installation.
is guaranteed never to change (although new species will be added
and existing species may have their names changed).
.IP \(bu
For each species marked in the bitmap, a two-octet
count of individuals. A zero means no count was given.
.IP \(bu
For each species marked in the bitmap, a comment
string.
.SH "AUTHOR"
Jörgen Grahn <jgrahn@algonet.se>
.SH "SEE ALSO"
.BR gavia (1)
