#!/usr/bin/perl -w # -*- perl -*-
#
# $Id: gavia_gab2roff,v 1.1 2002-09-29 19:44:37 grahn Exp $
# $Name:  $
#
# gavia_gab2text - transform gab (see gavia(5)) formatted excursions
# to roff (groff, nroff, troff) source
#
# Copyright (c) 2002 Jörgen Grahn <jgrahn@algonet.se>
# All rights reserved.
#

use strict;

while(<>) {
    print;
}

exit 0;
