#!/usr/bin/perl -w # -*- perl -*-
#
# $Id: gavia_focus,v 1.1 2001-09-23 20:20:08 grahn Exp $
# $Name:  $
#
# gaviafocus - remove certain species
# from a 'gab' file
#

use Getopt::Std;

getopt("f");

if(defined($opt_f)) {
    open BLACKLIST, $opt_f
	or die;
}
else {
    open BLACKLIST, glob("~/.gavia_focus")
	or
    open BLACKLIST, glob("~gavia/gavia_focus")
	or die;
}

my %blacklist;

while(<BLACKLIST>) {
    my $name;
    my $range;

    next if /^\#/;
    next if /^\s*$/;

    if(/\d/) {
	($name, $range) = /^\s*(.+?)\s*(\d+\-\d+)\s*$/;
	$blacklist{$name}=$range;
    }
    else {
	($name) = /^\s*(.+?)\s*$/;
	$blacklist{$name}="0101-1231";
    }
}

while(<>)
{
    if(/^date\s*:\s*(\d+)/i) {
	$date = $1 % 10000;
    }

    print, next
	unless /^[a-zедц \t]+:.+?:[0-9 \t]+?:/i;

    my ($name) = /\s*([a-zедц ]+?)\s*:/i
	or die;

    print, next unless defined($blacklist{$name});

    # print it anyways, iff out of blacklist range
    ($start, $end) = $blacklist{$name} =~ /(\d+)\-(\d+)/;
    if($start < $end) {
	print if $date<$start || $date>$end;
    }
    else {
	print if $date<$start && $date>$end;
    }
}

exit 0;
