#!/usr/bin/perl -w # -*- perl -*-
#
# $Id: gavia_score,v 1.3 2006-01-02 22:15:25 grahn Exp $
# $Name:  $
#
# gavia_score - find out how frequently different species are seen
#
# Copyright (c) 2002 Jörgen Grahn
# All rights reserved.
#

use strict;

my %species;

while(<>)
{
    next unless /^[a-zåäö \t]+:.+?:[0-9 \t]+?:/i;

    my ($name) = /\s*([a-zåäö ]+?)\s*:/i
	or die;

    if(not defined($species{$name})) {
	$species{$name} = 1;
	next;
    }

    $species{$name} += 1;
}

my $i;

foreach $i (keys %species) {
    print "$species{$i}  $i\n";
}

exit 0;
